services:
  postgres:
    image: postgres:15
    container_name: book_store_db
    environment:
      POSTGRES_DB: book_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
